server:
  port: 8083
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  resources:
    static-locations: file:${file.path}
  servlet:
    multipart:
      max-file-size: 10240000
      max-request-size: 10240000
  application:
#    name: crud-server
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///five?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
  jackson:
    date-format: yyyy-MM-dd
    default-property-inclusion: non_null
    time-zone: GMT+8
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
eureka:
  client:
    fetch-registry: true   #从注册中心拉出注册列表11
    service-url:
      defaultZone: http://localhost:8080/eureka
logging:
  file: d:/log/good-springboot.log
  level:
    com.start.mapper: debug
file:
  path: F:\\local\\image\\
  domain: http://127.0.0.1:8083/