server:
  port: 9999
spring:
  application:
#    name: zuul-server
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  max:
    host:
      connections: 500
  #请求头
  prefix: /api
  #不去掉所有前缀
  strip-prefix: true
  #自定义访问微服务的访问路径
  routes:  #路由
    user-routes:
      path: /consumer/**
      serviceId: crud-server
  #      strip-prefix: false

  #忽略
  ignored-services: '*'
  sensitive-headers:

#可以查看网关
management:
  endpoints:
    web:
      exposure:
        include: '*'
