server:
  port: 9999
  #servlet:
  #  context-path: /apollo/
spring:
  application:
#    name: gateway-server
    #getaway
  cloud:
    gateway:
      routes:
        - id : gateway-server
          uri: lb://gateway-server
          order: 0
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

eureka:
  client:
    fetch-registry: true   #从注册中心拉出注册列表
    service-url:
      defaultZone: http://localhost:8080/eureka

